spring:
  application:
    name: FcEurekaServer

server:
  port: 8081

eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://localhost:8082/eureka/,http://localhost:8083/eureka/
  instance:
    instance-id: eureka1

