server:
  port: 9010
spring:
  application:
    name: fc-mic-config
  cloud:
    config:
      label: master
      server:
        bootstrap: true
        git:
          uri: https://github.com/loyal2shrin/fc-mic.git
          search-paths: config
          username: 295905057@qq.com
          password: *********

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka
    instance:
      lease-renewal-interval-in-seconds: 10

logging:
  config: classpath:logback-spring.xml
