dubbo:
  application:
    name: fc-mic-consumer    #消费者名称
  registry:
    protocol: zookeeper #注册中心地址
    address: 172.31.57.77:2181,172.31.57.78:2181,172.31.57.79:2181
    id: lin-registry-1
  protocol:
    name: dubbo    #dubbo 协议