spring:
  application:
    name: fc-mic-mq

server:
  port: 8090

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka
#    instance:
#      lease-renewal-interval-in-seconds: 10
#    register-with-eureka: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka
    instance:
      lease-renewal-interval-in-seconds: 10

logging:
  config: classpath:logback-spring.xml
